### ISSUE TITLE
Automatically detect if stdin isn't a terminal

### ISSUE THREAD

**Issue by kopecs** [shwestrick/smlfmt#83]
It would be nice if `--stdio` wasn't required when stdin isn't a terminal. I think this should be as straightforward as the following, if there's interest:
```sml
val stdio = stdio orelse
              (* if stdin is not a terminal and an incompabible flag is not set, take input from stdin *)
              (not (Posix.ProcEnv.isatty Posix.FileSys.stdin)
                  andalso not (doForce orelse preview orelse previewOnly orelse not (List.null inputfiles)))
```
Given some POSIX APIs are already used this shouldn't impose any additional platform constraints.

Actually, given that `--stdio` isn't (yet) in a release, would just testing this be generally preferable, instead of a flag? I think this would still be fine for @azdavis too, given how millet would invoke.

**Comment by azdavis** [comment]
the only use case i can think of where you may want a stdio flag is if you actually are in a terminal but want to type input into stdin to the formatter, but that seems odd. and you might be able to just `cat | smlfmt` in that case anyway.

**Comment by shwestrick** [comment]
That seems like a nice idea. We could keep `--stdio` flag to let people force it if they'd like? And then the normal mode would adapt like you suggest.

@kopecs maybe you could make a PR?
